[book]
title = "Compiling Gleam to WebAssembly"
authors = ["Owais Jamil"]
language = "en"

[output.html]
theme = "theme"
default-theme = "day"
preferred-dark-theme = "night"
additional-css = ["src/assets/css/custom.css"]
git-repository-url = "https://github.com/desertthunder/regulus"
