[book]
title = "Compiling Gleam to WebAssembly"
authors = ["Owais Jamil"]
language = "en"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["src/assets/css/custom.css"]
git-repository-url = "https://github.com/desertthunder/regulus"
