const defaultWasmUrl = new URL("./__WASM_FILE__", import.meta.url);
const metadata = __REGULUS_JS_ABI_METADATA__;
const encoder = new TextEncoder();
const decoder = new TextDecoder();

let instance;
let memory;
let nextHandleId = 1;
const freeHandleIds = [];
const handles = new Map();

/**
 * Import and export ABI shapes generated by the compiler.
 *
 * Import keys use `module.name`, for example `regulus/js.request_text`.
 * Export keys use the public Wasm export name.
 */
export const abi = metadata;

/**
 * Stable browser-profile import function names.
 */
export const browserImportNames = Object.freeze({
  fetch: "fetch",
  localStorageGetItem: "localStorage.getItem",
  localStorageSetItem: "localStorage.setItem",
  localStorageRemoveItem: "localStorage.removeItem",
  timeNow: "time.now",
  onlineIsOnline: "online.isOnline",
});

/**
 * Stable Node.js-profile import function names.
 */
export const nodeImportNames = Object.freeze({
  envGet: "env.get",
  timeNow: "time.now",
});

/**
 * Instantiate the Regulus Wasm module and wrap host imports through the JS ABI.
 *
 * @param {URL|string|ArrayBuffer|ArrayBufferView|WebAssembly.Module} wasm Wasm
 *   module, bytes, or URL. Defaults to the generated sibling `.wasm` file.
 * @param {Record<string, Record<string, Function|object>>} imports Host imports.
 *   Bare functions use compiler metadata when present; object specs may provide
 *   `{ params, result, fn }` explicitly.
 * @returns {Promise<WebAssembly.Exports>} The instantiated Wasm exports.
 */
export async function init(wasm = defaultWasmUrl, imports = {}) {
  const wrappedImports = wrapImports(imports);
  if (wasm instanceof WebAssembly.Module) {
    instance = await WebAssembly.instantiate(wasm, wrappedImports);
  } else {
    const bytes = await readWasmBytes(wasm);
    const result = await WebAssembly.instantiate(bytes, wrappedImports);
    instance = result.instance;
  }
  memory = instance.exports.memory;
  if (!memory) {
    throw new Error("Regulus Wasm module does not export memory");
  }
  clearHandles();
  return instance.exports;
}

/**
 * Instantiate a Node.js-profile module from a filesystem `.wasm` artifact.
 *
 * Relative paths are resolved next to this generated adapter. URL, bytes, and
 * precompiled module inputs follow the same rules as `init`.
 *
 * @param {URL|string|ArrayBuffer|ArrayBufferView|WebAssembly.Module} wasm Wasm
 *   module, bytes, URL, or filesystem path. Defaults to the generated sibling
 *   `.wasm` file.
 * @param {Record<string, Record<string, Function|object>>} imports Host imports.
 * @param {object=} options Node API overrides passed to `createNodeImports`.
 * @returns {Promise<WebAssembly.Exports>} The instantiated Wasm exports.
 */
export async function initNode(wasm = defaultWasmUrl, imports = {}, options = {}) {
  return init(wasm, mergeImports(createNodeImports(options), imports));
}

/**
 * Instantiate a browser-profile module with the standard browser imports.
 *
 * @param {URL|string|ArrayBuffer|ArrayBufferView|WebAssembly.Module} wasm Wasm
 *   module, bytes, or URL. Defaults to the generated sibling `.wasm` file.
 * @param {Record<string, Record<string, Function|object>>=} imports
 *   Additional or overriding imports.
 * @param {object=} options Browser API overrides passed to
 *   `createBrowserImports`.
 * @returns {Promise<WebAssembly.Exports>} The instantiated Wasm exports.
 */
export async function initBrowserPage(wasm = defaultWasmUrl, imports = {}, options = {}) {
  return init(wasm, mergeImports(createBrowserImports(options), imports));
}

/**
 * Build the standard browser-profile imports.
 *
 * Returned functions use JavaScript values. `init` wraps them through the
 * generated ABI metadata before passing them to WebAssembly.instantiate.
 *
 * @param {object=} options Browser API overrides for tests or custom hosts.
 * @param {Function=} options.fetch Fetch implementation. Defaults to global
 *   `fetch` and returns the resulting Promise as an opaque handle.
 * @param {Storage=} options.localStorage Storage implementation. Defaults to
 *   global `localStorage`.
 * @param {Function=} options.now Clock implementation. Defaults to
 *   `Date.now` and returns Unix time in milliseconds.
 * @param {Navigator=} options.navigator Navigator implementation. Defaults to
 *   global `navigator`.
 * @returns {{ browser: Record<string, Function> }} Browser import module.
 */
export function createBrowserImports(options = {}) {
  const fetchFn = options.fetch ?? globalThis.fetch?.bind(globalThis);
  const storage = options.localStorage ?? globalThis.localStorage;
  const now = options.now ?? (() => Date.now());
  const navigator = options.navigator ?? globalThis.navigator;

  return {
    browser: {
      [browserImportNames.fetch](url) {
        if (typeof fetchFn !== "function") {
          throw new Error("browser.fetch import requires a fetch implementation");
        }
        return fetchFn(String(url));
      },
      [browserImportNames.localStorageGetItem](key) {
        ensureStorage(storage, "localStorage.getItem");
        return storage.getItem(String(key)) ?? "";
      },
      [browserImportNames.localStorageSetItem](key, value) {
        ensureStorage(storage, "localStorage.setItem");
        storage.setItem(String(key), String(value));
      },
      [browserImportNames.localStorageRemoveItem](key) {
        ensureStorage(storage, "localStorage.removeItem");
        storage.removeItem(String(key));
      },
      [browserImportNames.timeNow]() {
        return BigInt(Math.trunc(Number(now())));
      },
      [browserImportNames.onlineIsOnline]() {
        return Boolean(navigator?.onLine ?? true);
      },
    },
  };
}

/**
 * Build the standard Node.js-profile imports.
 *
 * Returned functions use JavaScript values. `initNode` wraps them through the
 * generated ABI metadata before passing them to WebAssembly.instantiate.
 *
 * @param {object=} options Node API overrides for tests or custom hosts.
 * @param {Record<string, string|undefined>=} options.env Environment map.
 *   Defaults to `process.env` when available.
 * @param {Function=} options.now Clock implementation. Defaults to
 *   `Date.now` and returns Unix time in milliseconds.
 * @returns {{ nodejs: Record<string, Function> }} Node import module.
 */
export function createNodeImports(options = {}) {
  const env = options.env ?? globalThis.process?.env ?? {};
  const now = options.now ?? (() => Date.now());

  return {
    nodejs: {
      [nodeImportNames.envGet](key) {
        return env[String(key)] ?? "";
      },
      [nodeImportNames.timeNow]() {
        return BigInt(Math.trunc(Number(now())));
      },
    },
  };
}

/**
 * Call an exported Gleam function using compiler-generated ABI metadata.
 *
 * @param {string} name Public export name.
 * @param {...unknown} args JavaScript arguments to convert into Wasm ABI values.
 * @returns {unknown} The converted JavaScript result.
 */
export function call(name, ...args) {
  const shape = exportShape(name);
  return callExport(name, shape.params, shape.result, ...args);
}

/**
 * Call an exported Gleam function with an explicit ABI shape.
 *
 * Prefer `call` when the generated adapter contains metadata. This lower-level
 * helper remains useful for handwritten adapters and tests.
 *
 * @param {string} name Public export name.
 * @param {string[]} paramTypes ABI parameter types.
 * @param {string} returnType ABI return type.
 * @param {...unknown} args JavaScript arguments to convert into Wasm ABI values.
 * @returns {unknown} The converted JavaScript result.
 */
export function callExport(name, paramTypes = [], returnType = "Nil", ...args) {
  ensureInstance();
  const fn = instance.exports[name];
  if (typeof fn !== "function") {
    throw new Error(`Regulus export "${name}" is not a function`);
  }
  if (args.length !== paramTypes.length) {
    throw new Error(
      `Regulus export "${name}" expects ${paramTypes.length} argument(s), got ${args.length}`,
    );
  }
  const mark = instance.exports.__regulus_arena_mark();
  try {
    const wasmArgs = args.map((arg, index) => toWasmValue(paramTypes[index], arg));
    return fromWasmValue(returnType, fn(...wasmArgs));
  } finally {
    instance.exports.__regulus_arena_reset(mark);
  }
}

/**
 * Build a reusable JavaScript wrapper for an exported Gleam function.
 *
 * @param {string} name Public export name.
 * @param {string[]=} paramTypes Optional explicit ABI parameter types. Omit to
 *   use generated metadata.
 * @param {string=} returnType Optional explicit ABI return type. Omit to use
 *   generated metadata.
 * @returns {Function} A JavaScript function that performs ABI conversion.
 */
export function exportFunction(name, paramTypes, returnType) {
  const shape = paramTypes
    ? { params: paramTypes, result: returnType ?? "Nil" }
    : exportShape(name);
  return (...args) => callExport(name, shape.params, shape.result, ...args);
}

/**
 * Call a string-only export. Kept for the first milestone examples.
 *
 * @param {string} name Public export name.
 * @param {...unknown} args Values converted to strings before crossing the ABI.
 * @returns {string} The decoded Gleam string result.
 */
export function callString(name, ...args) {
  return callExport(
    name,
    args.map(() => "String"),
    "String",
    ...args,
  );
}

/**
 * Build a reusable wrapper for a string-only export.
 *
 * @param {string} name Public export name.
 * @returns {Function} A JavaScript function that accepts string-like values and
 *   returns a JavaScript string.
 */
export function exportString(name) {
  return (...args) => callString(name, ...args);
}

/**
 * Encode a JavaScript string into guest memory and return a managed pointer.
 *
 * @param {unknown} value Value to stringify and encode as UTF-8.
 * @returns {number} Borrowed managed string pointer.
 */
export function writeString(value) {
  ensureInstance();
  const bytes = encoder.encode(String(value));
  const data = instance.exports.__regulus_alloc(bytes.length);
  new Uint8Array(memory.buffer, data, bytes.length).set(bytes);
  return instance.exports.__regulus_string_new(data, bytes.length);
}

/**
 * Decode a managed Gleam string pointer into a JavaScript string.
 *
 * @param {number} ptr Borrowed managed string pointer.
 * @returns {string} Decoded JavaScript string.
 */
export function readString(ptr) {
  ensureInstance();
  const len = instance.exports.__regulus_string_len(ptr);
  const data = instance.exports.__regulus_string_data(ptr);
  const bytes = new Uint8Array(memory.buffer, data, len);
  return decoder.decode(bytes);
}

/**
 * Read a borrowed managed pointer using a structured JS ABI shape.
 *
 * Shapes may be scalar names or objects such as `{ kind: "List", item }`,
 * `{ kind: "Tuple", items }`, `{ kind: "Record", fields }`,
 * `{ kind: "Result", ok, error }`, and `{ kind: "Option", some }`.
 *
 * @param {number} ptr Borrowed managed pointer.
 * @param {string|object} shape ABI reader shape.
 * @returns {unknown} Decoded JavaScript value.
 */
export function readValue(ptr, shape) {
  return fromWasmValue(shape, ptr);
}

/**
 * Encode a JavaScript JSON value into a managed Gleam `Dynamic` pointer.
 *
 * Accepted values are `null`, booleans, strings, finite numbers, arrays, and
 * plain objects with string keys. Integers are encoded as dynamic ints when
 * they fit the stable JS integer range; other numbers become dynamic floats.
 *
 * @param {unknown} value JavaScript JSON value.
 * @returns {number} Borrowed managed Dynamic pointer.
 */
export function writeDynamic(value) {
  ensureInstance();
  if (value === null) {
    return writeDynamicNil();
  }
  switch (typeof value) {
    case "boolean":
      return writeDynamicSlot(3, value ? 1n : 0n);
    case "string":
      return writeDynamicSlot(4, BigInt(writeString(value)));
    case "number":
      return writeDynamicNumber(value);
    case "bigint":
      return writeDynamicInt(value);
    case "object":
      if (Array.isArray(value)) {
        return writeDynamicArray(value);
      }
      return writeDynamicObject(value);
    default:
      throw new Error(`Cannot convert ${typeof value} to Gleam Dynamic`);
  }
}

/**
 * Parse JSON text and encode the result as a managed Gleam `Dynamic` pointer.
 *
 * @param {string} text JSON source text.
 * @returns {number} Borrowed managed Dynamic pointer.
 */
export function writeJson(text) {
  return writeDynamic(JSON.parse(String(text)));
}

/**
 * Decode a managed Gleam `Dynamic` pointer into a JavaScript JSON value.
 *
 * @param {number} ptr Borrowed managed Dynamic pointer.
 * @returns {unknown} JavaScript JSON value.
 */
export function readDynamic(ptr) {
  ensureValueTag(ptr, 5, "Dynamic");
  const dynamicTag = instance.exports.__regulus_value_constructor(ptr);
  switch (dynamicTag) {
    case 1:
      return instance.exports.__regulus_value_field(ptr, 0);
    case 2:
      return floatFromSlot(instance.exports.__regulus_value_field(ptr, 0));
    case 3:
      return instance.exports.__regulus_value_field(ptr, 0) !== 0n;
    case 4:
      return readString(pointerFromSlot(instance.exports.__regulus_value_field(ptr, 0)));
    case 6:
    case 9:
      return readDynamicArray(pointerFromSlot(instance.exports.__regulus_value_field(ptr, 0)));
    case 7:
      return null;
    case 8:
      return readDynamicObject(pointerFromSlot(instance.exports.__regulus_value_field(ptr, 0)));
    default:
      throw new Error(`Unsupported Gleam Dynamic tag ${dynamicTag}`);
  }
}

/**
 * Store a JavaScript value in the adapter handle table and return an opaque
 * Gleam pointer.
 *
 * @param {unknown} value JavaScript value to keep outside guest memory.
 * @param {number=} typeTag Stable host-defined opaque type tag.
 * @returns {number} Borrowed opaque managed pointer.
 */
export function wrapHandle(value, typeTag = 0) {
  ensureInstance();
  const id = allocateHandleId();
  handles.set(id, { value, typeTag: typeTag >>> 0 });
  return instance.exports.__regulus_handle_new(typeTag >>> 0, id);
}

/**
 * Resolve an opaque Gleam pointer back to its JavaScript value.
 *
 * @param {number} ptr Borrowed opaque managed pointer.
 * @param {number=} expectedTypeTag Optional expected opaque type tag.
 * @returns {unknown} JavaScript value stored in the adapter table.
 */
export function getHandle(ptr, expectedTypeTag) {
  const id = handleId(ptr, expectedTypeTag);
  const entry = handles.get(id);
  if (!entry) {
    throw new Error(`Regulus handle ${id} has been released or was not created by this adapter`);
  }
  return entry.value;
}

/**
 * Release one adapter-owned JavaScript handle.
 *
 * Releasing drops the adapter table reference. Existing opaque pointers with
 * the same handle id become invalid and must not be used again.
 *
 * @param {number} ptr Borrowed opaque managed pointer.
 * @param {number=} expectedTypeTag Optional expected opaque type tag.
 * @returns {boolean} True when a live handle was released.
 */
export function releaseHandle(ptr, expectedTypeTag) {
  const id = handleId(ptr, expectedTypeTag);
  if (!handles.delete(id)) {
    return false;
  }
  freeHandleIds.push(id);
  return true;
}

/**
 * Release every adapter-owned JavaScript handle.
 *
 * @returns {void}
 */
export function clearHandles() {
  handles.clear();
  freeHandleIds.length = 0;
  nextHandleId = 1;
}

/**
 * Read a tuple pointer as a JavaScript array.
 *
 * @param {number} ptr Borrowed tuple pointer.
 * @param {Array<string|object>} items Field shapes in tuple order.
 * @returns {unknown[]} Tuple fields.
 */
export function readTuple(ptr, items) {
  ensureValueTag(ptr, 3, "tuple");
  const arity = instance.exports.__regulus_value_arity(ptr);
  if (arity !== items.length) {
    throw new Error(`Regulus tuple arity ${arity} does not match shape arity ${items.length}`);
  }
  return items.map((item, index) => readField(ptr, index, item));
}

/**
 * Read a record pointer as a JavaScript object keyed by field name.
 *
 * @param {number} ptr Borrowed record pointer.
 * @param {Array<{ name: string, type: string|object }>} fields Field shapes in
 *   declaration order.
 * @returns {Record<string, unknown>} Record object.
 */
export function readRecord(ptr, fields) {
  ensureValueTag(ptr, 4, "record");
  const arity = instance.exports.__regulus_value_arity(ptr);
  if (arity !== fields.length) {
    throw new Error(`Regulus record arity ${arity} does not match shape arity ${fields.length}`);
  }
  const out = {};
  fields.forEach((field, index) => {
    out[field.name] = readField(ptr, index, field.type);
  });
  return out;
}

/**
 * Read a custom value pointer as `{ tag, fields }`.
 *
 * If `variants` maps constructor names to field shapes, the returned `tag` is
 * the constructor name. Otherwise `tag` is the numeric constructor tag.
 *
 * @param {number} ptr Borrowed custom value pointer.
 * @param {Record<string, { fields?: Array<string|object|{ name: string, type: string|object }> }}=} variants
 *   Optional variant shape map.
 * @returns {{ tag: string|number, fields: unknown[]|Record<string, unknown> }}
 *   Decoded custom value.
 */
export function readCustom(ptr, variants = {}) {
  ensureValueTag(ptr, 5, "custom value");
  const constructorTag = instance.exports.__regulus_value_constructor(ptr) >>> 0;
  const entry = Object.entries(variants).find(([name]) => constructorHash(name) === constructorTag);
  const name = entry?.[0];
  const variant = entry?.[1] ?? {};
  const fieldShapes = variant.fields ?? [];
  const arity = instance.exports.__regulus_value_arity(ptr);
  if (fieldShapes.length && arity !== fieldShapes.length) {
    throw new Error(
      `Regulus custom arity ${arity} does not match shape arity ${fieldShapes.length}`,
    );
  }
  const shapes = fieldShapes.length ? fieldShapes : Array.from({ length: arity }, () => "Int");
  const hasNamedFields = shapes.some((field) => typeof field === "object" && "name" in field);
  const fields = hasNamedFields ? {} : [];
  shapes.forEach((field, index) => {
    const fieldShape = field && typeof field === "object" && "type" in field ? field.type : field;
    const value = readField(ptr, index, fieldShape);
    if (hasNamedFields) {
      fields[field.name ?? String(index)] = value;
    } else {
      fields.push(value);
    }
  });
  return { tag: name ?? constructorTag, fields };
}

/**
 * Read a Gleam list pointer as a JavaScript array.
 *
 * @param {number} ptr Borrowed list pointer, or `0` for the empty list.
 * @param {string|object} item Item shape. Use `"String"` for lists of strings.
 * @returns {unknown[]} List items.
 */
export function readList(ptr, item) {
  const out = [];
  let cursor = ptr;
  while (cursor !== 0) {
    ensureValueTag(cursor, 2, "list cons cell");
    out.push(readField(cursor, 0, item));
    cursor = pointerFromSlot(instance.exports.__regulus_value_field(cursor, 1));
  }
  return out;
}

/**
 * Read a Gleam `Result(a, e)` pointer.
 *
 * @param {number} ptr Borrowed custom value pointer.
 * @param {string|object} ok Shape for the `Ok` payload.
 * @param {string|object} error Shape for the `Error` payload.
 * @returns {{ tag: "Ok", value: unknown }|{ tag: "Error", value: unknown }}
 *   Decoded result.
 */
export function readResult(ptr, ok, error) {
  ensureValueTag(ptr, 5, "Result");
  const tag = instance.exports.__regulus_value_constructor(ptr) >>> 0;
  if (tag === constructorHash("Ok")) {
    return { tag: "Ok", value: readField(ptr, 0, ok) };
  }
  if (tag === constructorHash("Error")) {
    return { tag: "Error", value: readField(ptr, 0, error) };
  }
  throw new Error(`Regulus custom value is not a Result constructor: ${tag}`);
}

/**
 * Read a Gleam `Option(a)` pointer.
 *
 * @param {number} ptr Borrowed custom value pointer.
 * @param {string|object} some Shape for the `Some` payload.
 * @returns {{ tag: "Some", value: unknown }|{ tag: "None" }} Decoded option.
 */
export function readOption(ptr, some) {
  ensureValueTag(ptr, 5, "Option");
  const tag = instance.exports.__regulus_value_constructor(ptr) >>> 0;
  if (tag === constructorHash("Some")) {
    return { tag: "Some", value: readField(ptr, 0, some) };
  }
  if (tag === constructorHash("None")) {
    return { tag: "None" };
  }
  throw new Error(`Regulus custom value is not an Option constructor: ${tag}`);
}

/**
 * Convert host imports into raw Wasm functions using compiler metadata.
 *
 * @param {Record<string, Record<string, Function|object>>} imports User imports.
 * @returns {WebAssembly.Imports} Imports ready for WebAssembly.instantiate.
 */
function wrapImports(imports) {
  const wrapped = {};
  for (const [moduleName, moduleImports] of Object.entries(imports)) {
    wrapped[moduleName] = {};
    for (const [name, importSpec] of Object.entries(moduleImports)) {
      const { fn, params, result } = normalizeImport(moduleName, name, importSpec);
      wrapped[moduleName][name] = (...args) => {
        if (args.length !== params.length) {
          throw new Error(
            `Regulus import "${moduleName}.${name}" expects ${params.length} argument(s), got ${args.length}`,
          );
        }
        const jsArgs = args.map((arg, index) => fromWasmValue(params[index], arg));
        return toWasmValue(result, fn(...jsArgs));
      };
    }
  }
  return wrapped;
}

/**
 * Normalize a bare import function or explicit import spec into one shape.
 *
 * @param {string} moduleName Import module name.
 * @param {string} name Import function name.
 * @param {Function|object} importSpec User-supplied import.
 * @returns {{ fn: Function, params: string[], result: string }} Import shape.
 */
function normalizeImport(moduleName, name, importSpec) {
  const shape = importShape(moduleName, name);
  if (typeof importSpec === "function") {
    return { fn: importSpec, params: shape.params, result: shape.result };
  }
  if (!importSpec || typeof importSpec.fn !== "function") {
    throw new Error(`Regulus import "${moduleName}.${name}" must be a function or import spec`);
  }
  return {
    fn: importSpec.fn,
    params: importSpec.params ?? shape.params,
    result: importSpec.result ?? shape.result,
  };
}

/**
 * Merge import modules. Later imports override earlier ones by module/name.
 *
 * @param {...Record<string, Record<string, Function|object>>} imports Import maps.
 * @returns {Record<string, Record<string, Function|object>>} Merged imports.
 */
function mergeImports(...imports) {
  const merged = {};
  for (const importMap of imports) {
    for (const [moduleName, moduleImports] of Object.entries(importMap ?? {})) {
      merged[moduleName] = { ...(merged[moduleName] ?? {}), ...moduleImports };
    }
  }
  return merged;
}

/**
 * Look up the ABI shape for a host import.
 *
 * @param {string} moduleName Import module name.
 * @param {string} name Import function name.
 * @returns {{ params: string[], result: string }} Import ABI shape.
 */
function importShape(moduleName, name) {
  const key = `${moduleName}.${name}`;
  const shape = metadata.imports[key];
  if (shape) {
    return shape;
  }
  return { params: ["String"], result: "String" };
}

/**
 * Look up the ABI shape for a public export.
 *
 * @param {string} name Public export name.
 * @returns {{ params: string[], result: string }} Export ABI shape.
 */
function exportShape(name) {
  const shape = metadata.exports[name];
  if (!shape) {
    throw new Error(`Regulus export "${name}" has no generated ABI metadata`);
  }
  return shape;
}

/**
 * Convert a JavaScript value to its raw Wasm ABI representation.
 *
 * @param {string} type ABI type name.
 * @param {unknown} value JavaScript value.
 * @returns {unknown} Raw Wasm-compatible value.
 */
function toWasmValue(type, value) {
  switch (type) {
    case "Int":
      return typeof value === "bigint" ? value : BigInt(value);
    case "Float":
      return Number(value);
    case "Bool":
      return value ? 1 : 0;
    case "String":
      return writeString(value);
    case "Dynamic":
      return writeDynamic(value);
    case "Handle":
      return typeof value === "number" ? value : wrapHandle(value);
    case "Nil":
      return undefined;
    default:
      throw new Error(`Unsupported Regulus JS ABI type "${type}"`);
  }
}

/**
 * Convert a raw Wasm ABI value to its JavaScript representation.
 *
 * @param {string} type ABI type name.
 * @param {unknown} value Raw Wasm value.
 * @returns {unknown} JavaScript value.
 */
function fromWasmValue(type, value) {
  if (type && typeof type === "object") {
    switch (type.kind) {
      case "Tuple":
        return readTuple(value, type.items ?? []);
      case "Record":
        return readRecord(value, type.fields ?? []);
      case "Custom":
        return readCustom(value, type.variants ?? {});
      case "List":
        return readList(value, type.item);
      case "Result":
        return readResult(value, type.ok, type.error);
      case "Option":
        return readOption(value, type.some);
      default:
        throw new Error(`Unsupported Regulus JS ABI shape "${type.kind}"`);
    }
  }
  switch (type) {
    case "Int":
      return value;
    case "Float":
      return value;
    case "Bool":
      return value !== 0;
    case "String":
      return readString(value);
    case "Dynamic":
      return readDynamic(value);
    case "Handle":
      return getHandle(value);
    case "Nil":
      return undefined;
    default:
      throw new Error(`Unsupported Regulus JS ABI type "${type}"`);
  }
}

/**
 * Read one raw object field and convert it through a shape.
 *
 * @param {number} ptr Borrowed managed pointer.
 * @param {number} index Field index.
 * @param {string|object} shape Field shape.
 * @returns {unknown} Converted field value.
 */
function readField(ptr, index, shape) {
  const slot = instance.exports.__regulus_value_field(ptr, index);
  if (shape === "String" || shape === "Dynamic" || (shape && typeof shape === "object")) {
    return fromWasmValue(shape, pointerFromSlot(slot));
  }
  if (shape === "Float") {
    return floatFromSlot(slot);
  }
  return fromWasmValue(shape, slot);
}

/**
 * Assert that a pointer has the expected runtime object tag.
 *
 * @param {number} ptr Borrowed managed pointer.
 * @param {number} expected Expected runtime object tag.
 * @param {string} name Human-readable shape name.
 * @returns {void}
 */
function ensureValueTag(ptr, expected, name) {
  if (ptr === 0) {
    throw new Error(`Regulus ${name} reader received null pointer`);
  }
  const actual = instance.exports.__regulus_value_tag(ptr);
  if (actual !== expected) {
    throw new Error(`Regulus ${name} reader expected tag ${expected}, got ${actual}`);
  }
}

/**
 * Read and validate an opaque handle id from guest memory.
 *
 * @param {number} ptr Borrowed opaque managed pointer.
 * @param {number|undefined} expectedTypeTag Optional expected opaque type tag.
 * @returns {number} Adapter handle table id.
 */
function handleId(ptr, expectedTypeTag) {
  ensureInstance();
  ensureValueTag(ptr, 8, "opaque handle");
  const actualTypeTag = instance.exports.__regulus_handle_type(ptr) >>> 0;
  if (expectedTypeTag !== undefined && actualTypeTag !== expectedTypeTag >>> 0) {
    throw new Error(
      `Regulus handle type ${actualTypeTag} does not match expected type ${expectedTypeTag >>> 0}`,
    );
  }
  return instance.exports.__regulus_handle_id(ptr) >>> 0;
}

/**
 * Allocate or reuse a table id for a JavaScript handle.
 *
 * @returns {number} Adapter-local handle id.
 */
function allocateHandleId() {
  const reused = freeHandleIds.pop();
  if (reused !== undefined) {
    return reused;
  }
  return nextHandleId++;
}

/**
 * Convert an i64 field slot containing a pointer in the low bits to a number.
 *
 * @param {bigint} slot Raw field slot.
 * @returns {number} Managed pointer.
 */
function pointerFromSlot(slot) {
  return Number(slot & 0xffff_ffffn);
}

/**
 * Reinterpret an i64 field slot as an IEEE-754 Float.
 *
 * @param {bigint} slot Raw field slot.
 * @returns {number} JavaScript number.
 */
function floatFromSlot(slot) {
  const buffer = new ArrayBuffer(8);
  const view = new DataView(buffer);
  view.setBigUint64(0, BigInt.asUintN(64, slot), true);
  return view.getFloat64(0, true);
}

/**
 * Reinterpret a JavaScript number as an IEEE-754 Float slot.
 *
 * @param {number} value JavaScript number.
 * @returns {bigint} Raw i64 slot bits.
 */
function slotFromFloat(value) {
  const buffer = new ArrayBuffer(8);
  const view = new DataView(buffer);
  view.setFloat64(0, value, true);
  return view.getBigUint64(0, true);
}

/**
 * Allocate a managed custom value.
 *
 * @param {number} constructor Constructor tag.
 * @param {bigint[]} fields Raw field slots.
 * @returns {number} Custom value pointer.
 */
function writeCustom(constructor, fields) {
  const ptr = instance.exports.__regulus_alloc(align8(12 + fields.length * 8));
  const view = new DataView(memory.buffer);
  view.setUint32(ptr, 5, true);
  view.setUint32(ptr + 4, fields.length, true);
  view.setUint32(ptr + 8, constructor >>> 0, true);
  fields.forEach((field, index) => {
    view.setBigUint64(ptr + 12 + index * 8, BigInt.asUintN(64, field), true);
  });
  return ptr;
}

/**
 * Allocate a managed tuple value.
 *
 * @param {bigint[]} fields Raw field slots.
 * @returns {number} Tuple pointer.
 */
function writeTuple(fields) {
  const ptr = instance.exports.__regulus_alloc(align8(8 + fields.length * 8));
  const view = new DataView(memory.buffer);
  view.setUint32(ptr, 3, true);
  view.setUint32(ptr + 4, fields.length, true);
  fields.forEach((field, index) => {
    view.setBigUint64(ptr + 8 + index * 8, BigInt.asUintN(64, field), true);
  });
  return ptr;
}

/**
 * Allocate a managed list cons cell.
 *
 * @param {bigint} head Raw head slot.
 * @param {number} tail Tail list pointer.
 * @returns {number} List cons pointer.
 */
function writeListCons(head, tail) {
  const ptr = instance.exports.__regulus_alloc(24);
  const view = new DataView(memory.buffer);
  view.setUint32(ptr, 2, true);
  view.setUint32(ptr + 4, 2, true);
  view.setBigUint64(ptr + 8, BigInt.asUintN(64, head), true);
  view.setUint32(ptr + 16, tail >>> 0, true);
  return ptr;
}

function writeDynamicSlot(tag, slot) {
  return writeCustom(tag, [slot]);
}

function writeDynamicNil() {
  return writeCustom(7, []);
}

function writeDynamicNumber(value) {
  if (!Number.isFinite(value)) {
    throw new Error("Cannot convert non-finite number to Gleam Dynamic");
  }
  if (Number.isSafeInteger(value)) {
    return writeDynamicInt(BigInt(value));
  }
  return writeDynamicSlot(2, slotFromFloat(value));
}

function writeDynamicInt(value) {
  return writeDynamicSlot(1, BigInt.asIntN(64, value));
}

function writeDynamicArray(items) {
  let list = 0;
  for (let index = items.length - 1; index >= 0; index -= 1) {
    list = writeListCons(BigInt(writeDynamic(items[index])), list);
  }
  return writeDynamicSlot(9, BigInt(list));
}

function writeDynamicObject(value) {
  if (!value || Object.getPrototypeOf(value) !== Object.prototype) {
    throw new Error("Cannot convert non-plain object to Gleam Dynamic");
  }
  const entries = Object.entries(value);
  const buckets = instance.exports.__regulus_alloc(64);
  new Uint8Array(memory.buffer, buckets, 64).fill(0);
  let bucket = 0;
  for (let index = entries.length - 1; index >= 0; index -= 1) {
    const [key, item] = entries[index];
    const pair = writeTuple([BigInt(writeDynamic(key)), BigInt(writeDynamic(item))]);
    bucket = writeListCons(BigInt(pair), bucket);
  }
  new DataView(memory.buffer).setUint32(buckets, bucket >>> 0, true);
  const dict = writeCustom(4134106229, [BigInt(entries.length), 16n, BigInt(buckets)]);
  return writeDynamicSlot(8, BigInt(dict));
}

function readDynamicArray(ptr) {
  const out = [];
  let cursor = ptr;
  while (cursor !== 0) {
    ensureValueTag(cursor, 2, "dynamic array cons cell");
    out.push(readDynamic(pointerFromSlot(instance.exports.__regulus_value_field(cursor, 0))));
    cursor = pointerFromSlot(instance.exports.__regulus_value_field(cursor, 1));
  }
  return out;
}

function readDynamicObject(dict) {
  ensureValueTag(dict, 5, "dynamic properties dictionary");
  const buckets = pointerFromSlot(instance.exports.__regulus_value_field(dict, 2));
  const view = new DataView(memory.buffer);
  const out = {};
  for (let index = 0; index < 16; index += 1) {
    let bucket = view.getUint32(buckets + index * 4, true);
    while (bucket !== 0) {
      ensureValueTag(bucket, 2, "dynamic properties bucket");
      const pair = pointerFromSlot(instance.exports.__regulus_value_field(bucket, 0));
      ensureValueTag(pair, 3, "dynamic properties pair");
      const key = readDynamic(pointerFromSlot(instance.exports.__regulus_value_field(pair, 0)));
      if (typeof key !== "string") {
        throw new Error("Gleam Dynamic properties contain a non-string key");
      }
      out[key] = readDynamic(pointerFromSlot(instance.exports.__regulus_value_field(pair, 1)));
      bucket = pointerFromSlot(instance.exports.__regulus_value_field(bucket, 1));
    }
  }
  return out;
}

function align8(value) {
  return (value + 7) & -8;
}

/**
 * Compute the stable constructor tag used by the Wasm backend.
 *
 * @param {string} name Constructor name.
 * @returns {number} Unsigned 32-bit constructor tag.
 */
function constructorHash(name) {
  let hash = 0x811c_9dc5;
  for (const char of new TextEncoder().encode(name)) {
    hash = Math.imul(hash, 0x0100_0193) ^ char;
  }
  return hash >>> 0;
}

/**
 * Check that a browser storage object is available before an import uses it.
 *
 * @param {Storage|undefined} storage Browser storage object.
 * @param {string} importName Import name for diagnostics.
 * @returns {void}
 */
function ensureStorage(storage, importName) {
  if (!storage) {
    throw new Error(`browser.${importName} import requires localStorage`);
  }
}

/**
 * Load Wasm bytes from a buffer, typed array, URL, or path-like string.
 *
 * @param {URL|string|ArrayBuffer|ArrayBufferView} wasm Wasm source.
 * @returns {Promise<ArrayBuffer|ArrayBufferView>} Wasm bytes.
 */
async function readWasmBytes(wasm) {
  if (wasm instanceof ArrayBuffer || ArrayBuffer.isView(wasm)) {
    return wasm;
  }
  const url = wasm instanceof URL ? wasm : new URL(wasm, import.meta.url);
  if (url.protocol === "file:") {
    const fs = await import("node:fs/promises");
    return fs.readFile(url);
  }
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Could not fetch Wasm artifact: ${response.status}`);
  }
  return response.arrayBuffer();
}

/**
 * Ensure `init` has completed before helper calls touch memory or exports.
 *
 * @returns {void}
 */
function ensureInstance() {
  if (!instance || !memory) {
    throw new Error("Regulus Wasm module has not been initialized");
  }
}
